name: workflow
on: [push]
jobs:
   tests:
      runs-on: ubunti-latest
      steps:
         -name: checking for python
         run: python --version; pip version
         -name: intstall numpy:
         run: pip install -U numpy
         -uses: actions/checkout@v1 ###actually loads the repo
         -name: run main.py
         run: python main.py
